In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
df = pd.read_csv("survey lung cancer.csv")

In [17]:
df

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

### Check for duplicates

In [18]:
df = df.drop_duplicates()

In [19]:
from sklearn.preprocessing import LabelEncoder

encode = LabelEncoder()

df["GENDER"] = encode.fit_transform(df['GENDER'])
df['LUNG_CANCER'] = encode.fit_transform(df['LUNG_CANCER'])

C:\Users\DELL\AppData\Local\Temp\ipykernel_20944\4008941447.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["GENDER"] = encode.fit_transform(df['GENDER'])
C:\Users\DELL\AppData\Local\Temp\ipykernel_20944\4008941447.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['LUNG_CANCER'] = encode.fit_transform(df['LUNG_CANCER'])

In [20]:
df.columns

Index(['GENDER', 'AGE', 'SMOKING', 'YELLOW_FINGERS', 'ANXIETY',
       'PEER_PRESSURE', 'CHRONIC DISEASE', 'FATIGUE ', 'ALLERGY ', 'WHEEZING',
       'ALCOHOL CONSUMING', 'COUGHING', 'SHORTNESS OF BREATH',
       'SWALLOWING DIFFICULTY', 'CHEST PAIN', 'LUNG_CANCER'],
      dtype='object')

In [10]:
df.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,1,69,0,2,2,1,1,2,1,2,2,2,2,2,2,1
1,1,74,1,1,1,1,2,2,2,1,1,1,2,2,2,1
2,0,59,0,1,1,2,1,2,1,2,1,2,2,1,2,0
3,1,63,1,2,2,1,1,1,1,1,2,1,1,2,2,0
4,0,63,0,2,1,1,1,1,1,2,1,2,2,1,1,0

In [21]:
df['SMOKING'] = df['SMOKING'].map({
    1:0,2:1
})

df['YELLOW_FINGERS'] = df['YELLOW_FINGERS'].map({
    1:0,2:1
})

df['ANXIETY'] = df['ANXIETY'].map({1:0,2:1})
df['PEER_PRESSURE'] = df['PEER_PRESSURE'].map({1:0,2:1})
df['CHRONIC DISEASE'] = df['CHRONIC DISEASE'].map({1:0,2:1})
df['FATIGUE '] = df['FATIGUE '].map({1:0,2:1})
df['ALLERGY'] = df['ALLERGY '].map({1:0,2:1})
df['WHEEZING'] = df['WHEEZING'].map({1:0,2:1})
df['ALCOHOL CONSUMING'] = df['ALCOHOL CONSUMING'].map({1:0,2:1})
df['COUGHING'] = df['COUGHING'].map({1:0,2:1})
df['SHORTNESS OF BREATH'] = df['SHORTNESS OF BREATH'].map({1:0,2:1})
df['SWALLOWING DIFFICULTY'] = df['SWALLOWING DIFFICULTY'].map({1:0,2:1})
df['CHEST PAIN'] = df['CHEST PAIN'].map({1:0,2:1})

C:\Users\DELL\AppData\Local\Temp\ipykernel_20944\2333082669.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['SMOKING'] = df['SMOKING'].map({
C:\Users\DELL\AppData\Local\Temp\ipykernel_20944\2333082669.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['YELLOW_FINGERS'] = df['YELLOW_FINGERS'].map({
C:\Users\DELL\AppData\Local\Temp\ipykernel_20944\2333082669.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ANXIETY'] = df['ANXIETY'].map({1:0,2:1})
C:\Users\DELL\AppData\Local\Temp\ipykernel_20944\2333082669.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['PEER_PRESSURE'] = df['PEER_PRESSURE'].map({1:0,2:1})
C:\Users\DELL\AppData\Local\Temp\ipykernel_20944\2333082669.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CHRONIC DISEASE'] = df['CHRONIC DISEASE'].map({1:0,2:1})
C:\Users\DELL\AppData\Local\Temp\ipykernel_20944\2333082669.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FATIGUE '] = df['FATIGUE '].map({1:0,2:1})
C:\Users\DELL\AppData\Local\Temp\ipykernel_20944\2333082669.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ALLERGY'] = df['ALLERGY '].map({1:0,2:1})
C:\Users\DELL\AppData\Local\Temp\ipykernel_20944\2333082669.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['WHEEZING'] = df['WHEEZING'].map({1:0,2:1})
C:\Users\DELL\AppData\Local\Temp\ipykernel_20944\2333082669.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ALCOHOL CONSUMING'] = df['ALCOHOL CONSUMING'].map({1:0,2:1})
C:\Users\DELL\AppData\Local\Temp\ipykernel_20944\2333082669.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['COUGHING'] = df['COUGHING'].map({1:0,2:1})
C:\Users\DELL\AppData\Local\Temp\ipykernel_20944\2333082669.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['SHORTNESS OF BREATH'] = df['SHORTNESS OF BREATH'].map({1:0,2:1})
C:\Users\DELL\AppData\Local\Temp\ipykernel_20944\2333082669.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['SWALLOWING DIFFICULTY'] = df['SWALLOWING DIFFICULTY'].map({1:0,2:1})
C:\Users\DELL\AppData\Local\Temp\ipykernel_20944\2333082669.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CHEST PAIN'] = df['CHEST PAIN'].map({1:0,2:1})

In [22]:
df.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER,ALLERGY
0,1,69,0,1,1,0,0,1,1,1,1,1,1,1,1,1,0
1,1,74,1,0,0,0,1,1,2,0,0,0,1,1,1,1,1
2,0,59,0,0,0,1,0,1,1,1,0,1,1,0,1,0,0
3,1,63,1,1,1,0,0,0,1,0,1,0,0,1,1,0,0
4,0,63,0,1,0,0,0,0,1,1,0,1,1,0,0,0,0

In [23]:
df.isna().sum()

GENDER                   0
AGE                      0
SMOKING                  0
YELLOW_FINGERS           0
ANXIETY                  0
PEER_PRESSURE            0
CHRONIC DISEASE          0
FATIGUE                  0
ALLERGY                  0
WHEEZING                 0
ALCOHOL CONSUMING        0
COUGHING                 0
SHORTNESS OF BREATH      0
SWALLOWING DIFFICULTY    0
CHEST PAIN               0
LUNG_CANCER              0
ALLERGY                  0
dtype: int64

In [35]:
df['LUNG_CANCER'].value_counts(normalize=True)

LUNG_CANCER
1    0.862319
0    0.137681
Name: proportion, dtype: float64

#### Spliting Data

In [25]:
from sklearn.model_selection import train_test_split


x = df.drop(["LUNG_CANCER"],axis=1)
y = df['LUNG_CANCER']

In [26]:
x

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,ALLERGY
0,1,69,0,1,1,0,0,1,1,1,1,1,1,1,1,0
1,1,74,1,0,0,0,1,1,2,0,0,0,1,1,1,1
2,0,59,0,0,0,1,0,1,1,1,0,1,1,0,1,0
3,1,63,1,1,1,0,0,0,1,0,1,0,0,1,1,0
4,0,63,0,1,0,0,0,0,1,1,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,0,59,0,1,1,1,0,0,2,1,0,1,0,1,0,1
280,0,59,1,0,0,0,1,1,2,0,0,0,1,0,0,1
281,1,55,1,0,0,0,0,1,2,0,0,0,1,0,1,1
282,1,46,0,1,1,0,0,0,1,0,0,0,0,1,1,0
283,1,60,0,1,1,0,0,1,1,1,1,1,1,1,1,0

In [27]:
y

0      1
1      1
2      0
3      0
4      0
      ..
279    1
280    0
281    0
282    0
283    1
Name: LUNG_CANCER, Length: 276, dtype: int32

In [28]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,stratify=y,random_state=42)

In [29]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()

x_train_s,y_train_s = smote.fit_resample(x_train,y_train)

In [32]:
y_train_s.value_counts()

LUNG_CANCER
1    179
0    179
Name: count, dtype: int64

In [34]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,recall_score,precision_score,classification_report

model = XGBClassifier(n_estimators=200,learning_rate=0.8,subsample=0.8,max_depth=3,random_state=12)

model.fit(x_train_s,y_train_s)

pred = model.predict(x_test)

acc = accuracy_score(y_test,pred)
rec = recall_score(y_test,pred)
pre = precision_score(y_test,pred)

print(f"Accuracy Score: {acc}\n Recall Score: {rec} \n Precision Score: {pre}")
print(classification_report(y_test,pred))

Accuracy Score: 0.8985507246376812
 Recall Score: 0.9661016949152542
 Precision Score: 0.9193548387096774
              precision    recall  f1-score   support

           0       0.71      0.50      0.59        10
           1       0.92      0.97      0.94        59

    accuracy                           0.90        69
   macro avg       0.82      0.73      0.77        69
weighted avg       0.89      0.90      0.89        69

In [42]:
import optuna
from xgboost import XGBClassifier
from sklearn.metrics import recall_score
from sklearn.model_selection import train_test_split

# Objective function for Optuna
def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 300, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 1),
        "max_depth": trial.suggest_int("max_depth", 0, 20),
        "subsample": trial.suggest_float("subsample", 0.2, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.2, 1.0),
        "min_child_weight": trial.suggest_int("min_child_weight", 0, 20),
        "gamma": trial.suggest_float("gamma", 0, 20),
        "reg_alpha": trial.suggest_float("reg_alpha", 0, 20),
        "reg_lambda": trial.suggest_float("reg_lambda", 0, 20),
        "random_state": 42,
        "n_jobs": -1,
        "scale_pos_weight": (y_train_s == 0).sum() / (y_train_s == 1).sum(),
        "eval_metric": "logloss"
    }
    
    # THRESHOLD = 0.25
    
    model = XGBClassifier(**params)
    model.fit(x_train_s, y_train_s)
    proba = model.predict_proba(x_test)[:, 1]
    # y_pred = (proba >= THRESHOLD).astype(int)  # Keep your tuned threshold
    y_pred = model.predict(x_test)
    print(f"Accuracy Score: {accuracy_score(y_test,y_pred)}")
    return recall_score(y_test, y_pred)  # Optimize recall for churners

# Run Optuna
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=30)

print("Best Params:", study.best_params)
print("Best Recall:", study.best_value)

params = study.best_params

[I 2026-07-30 13:37:58,465] A new study created in memory with name: no-name-2f71007b-1b83-49d3-8b6b-d967d9befc00
[I 2026-07-30 13:37:59,666] Trial 0 finished with value: 0.6101694915254238 and parameters: {'n_estimators': 437, 'learning_rate': 0.3536394964043193, 'max_depth': 2, 'subsample': 0.5197658374219759, 'colsample_bytree': 0.30307067695407675, 'min_child_weight': 20, 'gamma': 4.982701350017054, 'reg_alpha': 2.856031289166503, 'reg_lambda': 14.256259170413157}. Best is trial 0 with value: 0.6101694915254238.

Accuracy Score: 0.6086956521739131

[I 2026-07-30 13:38:00,619] Trial 1 finished with value: 0.0 and parameters: {'n_estimators': 529, 'learning_rate': 0.36187993901039733, 'max_depth': 2, 'subsample': 0.2900982886404608, 'colsample_bytree': 0.5683070508294358, 'min_child_weight': 0, 'gamma': 19.80456091281917, 'reg_alpha': 16.252835548965827, 'reg_lambda': 18.1439102783165}. Best is trial 0 with value: 0.6101694915254238.

Accuracy Score: 0.14492753623188406

[I 2026-07-30 13:38:01,524] Trial 2 finished with value: 0.8135593220338984 and parameters: {'n_estimators': 457, 'learning_rate': 0.22862129028120518, 'max_depth': 8, 'subsample': 0.6701287455545321, 'colsample_bytree': 0.5341064018306194, 'min_child_weight': 11, 'gamma': 7.560551942978353, 'reg_alpha': 13.238038818717367, 'reg_lambda': 13.58795829765414}. Best is trial 2 with value: 0.8135593220338984.

Accuracy Score: 0.7971014492753623

[I 2026-07-30 13:38:02,135] Trial 3 finished with value: 0.9830508474576272 and parameters: {'n_estimators': 634, 'learning_rate': 0.0834406171723694, 'max_depth': 19, 'subsample': 0.9560301670686766, 'colsample_bytree': 0.5610548250635559, 'min_child_weight': 18, 'gamma': 15.437091403894819, 'reg_alpha': 2.253803670031582, 'reg_lambda': 11.129358439611085}. Best is trial 3 with value: 0.9830508474576272.

Accuracy Score: 0.9420289855072463

[I 2026-07-30 13:38:02,716] Trial 4 finished with value: 0.7457627118644068 and parameters: {'n_estimators': 424, 'learning_rate': 0.7139900391478692, 'max_depth': 15, 'subsample': 0.9039368720038503, 'colsample_bytree': 0.5324691439072234, 'min_child_weight': 16, 'gamma': 13.702126111768099, 'reg_alpha': 17.050030722588996, 'reg_lambda': 12.448468573034281}. Best is trial 3 with value: 0.9830508474576272.

Accuracy Score: 0.7681159420289855

[I 2026-07-30 13:38:03,245] Trial 5 finished with value: 0.9661016949152542 and parameters: {'n_estimators': 316, 'learning_rate': 0.46753497786761256, 'max_depth': 0, 'subsample': 0.5192226205248442, 'colsample_bytree': 0.8771471747081523, 'min_child_weight': 5, 'gamma': 6.305170054975013, 'reg_alpha': 0.9506405244009586, 'reg_lambda': 5.971566425157741}. Best is trial 3 with value: 0.9830508474576272.

Accuracy Score: 0.927536231884058

[I 2026-07-30 13:38:04,364] Trial 6 finished with value: 0.9152542372881356 and parameters: {'n_estimators': 700, 'learning_rate': 0.0384133845869854, 'max_depth': 14, 'subsample': 0.9250708127054177, 'colsample_bytree': 0.2577206090795785, 'min_child_weight': 11, 'gamma': 8.611646963792614, 'reg_alpha': 16.197363586925782, 'reg_lambda': 5.543488457651227}. Best is trial 3 with value: 0.9830508474576272.

Accuracy Score: 0.8840579710144928

[I 2026-07-30 13:38:04,747] Trial 7 finished with value: 0.9661016949152542 and parameters: {'n_estimators': 345, 'learning_rate': 0.090410605260407, 'max_depth': 8, 'subsample': 0.7428380715426184, 'colsample_bytree': 0.8987469907695314, 'min_child_weight': 9, 'gamma': 1.920166871033131, 'reg_alpha': 7.299122608948894, 'reg_lambda': 6.268252212543278}. Best is trial 3 with value: 0.9830508474576272.

Accuracy Score: 0.927536231884058

[I 2026-07-30 13:38:05,253] Trial 8 finished with value: 0.9661016949152542 and parameters: {'n_estimators': 606, 'learning_rate': 0.5695183809577089, 'max_depth': 8, 'subsample': 0.8776776782927775, 'colsample_bytree': 0.6981612040078797, 'min_child_weight': 4, 'gamma': 0.011901876038191705, 'reg_alpha': 2.889940739996959, 'reg_lambda': 16.1123817176566}. Best is trial 3 with value: 0.9830508474576272.

Accuracy Score: 0.927536231884058

[I 2026-07-30 13:38:05,854] Trial 9 finished with value: 0.8813559322033898 and parameters: {'n_estimators': 817, 'learning_rate': 0.6673918797506562, 'max_depth': 9, 'subsample': 0.8004325175272531, 'colsample_bytree': 0.5125339865395971, 'min_child_weight': 1, 'gamma': 8.52492072198342, 'reg_alpha': 12.540766638201827, 'reg_lambda': 7.14329425650539}. Best is trial 3 with value: 0.9830508474576272.

Accuracy Score: 0.855072463768116

[I 2026-07-30 13:38:07,065] Trial 10 finished with value: 1.0 and parameters: {'n_estimators': 923, 'learning_rate': 0.9000473974398545, 'max_depth': 20, 'subsample': 0.22377610769267686, 'colsample_bytree': 0.7491046922883842, 'min_child_weight': 20, 'gamma': 14.19844201919541, 'reg_alpha': 7.311873826193983, 'reg_lambda': 1.0929293887994351}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.855072463768116

[I 2026-07-30 13:38:07,915] Trial 11 finished with value: 0.0 and parameters: {'n_estimators': 1000, 'learning_rate': 0.9204249674043476, 'max_depth': 19, 'subsample': 0.20074882055705207, 'colsample_bytree': 0.7289712855006998, 'min_child_weight': 20, 'gamma': 13.672999673959627, 'reg_alpha': 8.4479334311646, 'reg_lambda': 1.2107483964762729}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.14492753623188406

[I 2026-07-30 13:38:08,569] Trial 12 finished with value: 0.6949152542372882 and parameters: {'n_estimators': 836, 'learning_rate': 0.946277437460768, 'max_depth': 20, 'subsample': 0.37384483361242393, 'colsample_bytree': 0.719522776629306, 'min_child_weight': 16, 'gamma': 15.21667124923728, 'reg_alpha': 5.6938272843887345, 'reg_lambda': 0.3416258760087981}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.6811594202898551

[I 2026-07-30 13:38:09,374] Trial 13 finished with value: 0.8305084745762712 and parameters: {'n_estimators': 747, 'learning_rate': 0.7782787691748162, 'max_depth': 16, 'subsample': 0.47299744910183006, 'colsample_bytree': 0.3664851780219871, 'min_child_weight': 16, 'gamma': 16.90659828406217, 'reg_alpha': 5.06664515622629, 'reg_lambda': 10.218332277884759}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.8115942028985508

[I 2026-07-30 13:38:10,617] Trial 14 finished with value: 0.864406779661017 and parameters: {'n_estimators': 999, 'learning_rate': 0.14628326473879882, 'max_depth': 17, 'subsample': 0.6674767453132144, 'colsample_bytree': 0.4299848002693428, 'min_child_weight': 17, 'gamma': 11.704074850824144, 'reg_alpha': 10.457582696665794, 'reg_lambda': 9.059685966161119}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.8405797101449275

[I 2026-07-30 13:38:11,742] Trial 15 finished with value: 0.9152542372881356 and parameters: {'n_estimators': 610, 'learning_rate': 0.804444976926599, 'max_depth': 12, 'subsample': 0.9950449968320949, 'colsample_bytree': 0.790655650023408, 'min_child_weight': 13, 'gamma': 18.618873091281586, 'reg_alpha': 0.8245997335190012, 'reg_lambda': 3.1235269471285947}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.8695652173913043

[I 2026-07-30 13:38:12,525] Trial 16 finished with value: 0.6949152542372882 and parameters: {'n_estimators': 892, 'learning_rate': 0.5368134135368337, 'max_depth': 18, 'subsample': 0.3908451980455694, 'colsample_bytree': 0.9964081228702979, 'min_child_weight': 19, 'gamma': 11.359572682320017, 'reg_alpha': 4.4786777277563985, 'reg_lambda': 10.67842815866382}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.6811594202898551

[I 2026-07-30 13:38:13,473] Trial 17 finished with value: 0.0 and parameters: {'n_estimators': 705, 'learning_rate': 0.2723882962978348, 'max_depth': 12, 'subsample': 0.21490408997056087, 'colsample_bytree': 0.6858139460212359, 'min_child_weight': 14, 'gamma': 16.288486076546018, 'reg_alpha': 9.54218780183587, 'reg_lambda': 3.4716116927659213}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.14492753623188406

[I 2026-07-30 13:38:14,545] Trial 18 finished with value: 0.7966101694915254 and parameters: {'n_estimators': 906, 'learning_rate': 0.9965904014603331, 'max_depth': 20, 'subsample': 0.5980373643724689, 'colsample_bytree': 0.627610016080977, 'min_child_weight': 18, 'gamma': 12.08399426822718, 'reg_alpha': 6.19407736313414, 'reg_lambda': 19.034960498043247}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.7971014492753623

[I 2026-07-30 13:38:15,546] Trial 19 finished with value: 0.8135593220338984 and parameters: {'n_estimators': 537, 'learning_rate': 0.41438833725581736, 'max_depth': 5, 'subsample': 0.7728084387182128, 'colsample_bytree': 0.4338902615726192, 'min_child_weight': 14, 'gamma': 18.092074714712194, 'reg_alpha': 19.651047092022868, 'reg_lambda': 8.299289062473278}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.7971014492753623

[I 2026-07-30 13:38:16,753] Trial 20 finished with value: 0.0 and parameters: {'n_estimators': 770, 'learning_rate': 0.6077735910745643, 'max_depth': 13, 'subsample': 0.33250968862089836, 'colsample_bytree': 0.8355297612638037, 'min_child_weight': 7, 'gamma': 14.653950743768895, 'reg_alpha': 11.54751674663536, 'reg_lambda': 11.255368377346251}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.14492753623188406

[I 2026-07-30 13:38:17,915] Trial 21 finished with value: 0.9661016949152542 and parameters: {'n_estimators': 304, 'learning_rate': 0.5005838280526099, 'max_depth': 0, 'subsample': 0.47492752198532845, 'colsample_bytree': 0.9185448563344846, 'min_child_weight': 5, 'gamma': 5.746832992853595, 'reg_alpha': 0.5743741932795692, 'reg_lambda': 3.8616362556258292}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.927536231884058

[I 2026-07-30 13:38:18,465] Trial 22 finished with value: 0.9661016949152542 and parameters: {'n_estimators': 536, 'learning_rate': 0.8430951129946946, 'max_depth': 6, 'subsample': 0.5175045911014163, 'colsample_bytree': 0.8100469552228878, 'min_child_weight': 4, 'gamma': 5.171483128130346, 'reg_alpha': 2.751448872805665, 'reg_lambda': 2.024817501750752}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.9130434782608695

[I 2026-07-30 13:38:19,198] Trial 23 finished with value: 0.9661016949152542 and parameters: {'n_estimators': 373, 'learning_rate': 0.21879615750511971, 'max_depth': 17, 'subsample': 0.27920451192498313, 'colsample_bytree': 0.649967358960168, 'min_child_weight': 8, 'gamma': 10.148262549221057, 'reg_alpha': 0.1336514740384862, 'reg_lambda': 4.550273912760206}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.9710144927536232

[I 2026-07-30 13:38:19,898] Trial 24 finished with value: 0.9661016949152542 and parameters: {'n_estimators': 625, 'learning_rate': 0.4439987990988183, 'max_depth': 11, 'subsample': 0.5940655857466492, 'colsample_bytree': 0.8934015354974538, 'min_child_weight': 6, 'gamma': 12.79452336559504, 'reg_alpha': 3.490287978381308, 'reg_lambda': 7.750411218233907}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.9420289855072463

[I 2026-07-30 13:38:21,283] Trial 25 finished with value: 0.9661016949152542 and parameters: {'n_estimators': 891, 'learning_rate': 0.6866894683922343, 'max_depth': 5, 'subsample': 0.41392454119977995, 'colsample_bytree': 0.9997436823523933, 'min_child_weight': 3, 'gamma': 2.6815669359241934, 'reg_alpha': 1.6577592945351953, 'reg_lambda': 5.622870909356456}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.8985507246376812

[I 2026-07-30 13:38:22,187] Trial 26 finished with value: 0.9491525423728814 and parameters: {'n_estimators': 494, 'learning_rate': 0.30410744368899867, 'max_depth': 18, 'subsample': 0.6611789352527052, 'colsample_bytree': 0.7743121229092859, 'min_child_weight': 18, 'gamma': 16.187123907622908, 'reg_alpha': 7.4404542321060925, 'reg_lambda': 2.5190898208885515}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.8840579710144928

[I 2026-07-30 13:38:22,883] Trial 27 finished with value: 0.9830508474576272 and parameters: {'n_estimators': 687, 'learning_rate': 0.14346748159889333, 'max_depth': 15, 'subsample': 0.8391977656588854, 'colsample_bytree': 0.8491444576125518, 'min_child_weight': 12, 'gamma': 6.880944057448165, 'reg_alpha': 1.7739974241833103, 'reg_lambda': 0.1902174377485798}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.9420289855072463

[I 2026-07-30 13:38:23,624] Trial 28 finished with value: 0.9491525423728814 and parameters: {'n_estimators': 678, 'learning_rate': 0.17532934075874884, 'max_depth': 15, 'subsample': 0.9776954459287781, 'colsample_bytree': 0.6014209625449837, 'min_child_weight': 13, 'gamma': 10.319495350371344, 'reg_alpha': 4.1976192436132, 'reg_lambda': 0.7126262528098004}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.9130434782608695

[I 2026-07-30 13:38:24,863] Trial 29 finished with value: 0.9491525423728814 and parameters: {'n_estimators': 754, 'learning_rate': 0.029311358073120408, 'max_depth': 20, 'subsample': 0.8476091234332731, 'colsample_bytree': 0.45947926470507017, 'min_child_weight': 20, 'gamma': 3.0779319363171105, 'reg_alpha': 2.083175863491494, 'reg_lambda': 15.391943834005106}. Best is trial 10 with value: 1.0.

Accuracy Score: 0.927536231884058
Best Params: {'n_estimators': 923, 'learning_rate': 0.9000473974398545, 'max_depth': 20, 'subsample': 0.22377610769267686, 'colsample_bytree': 0.7491046922883842, 'min_child_weight': 20, 'gamma': 14.19844201919541, 'reg_alpha': 7.311873826193983, 'reg_lambda': 1.0929293887994351}
Best Recall: 1.0

In [44]:
best_model = XGBClassifier(n_estimators= 634,learning_rate= 0.0834406171723694,max_depth= 19,subsample= 0.9560301670686766,colsample_bytree= 0.5610548250635559,min_child_weight= 18,gamma= 15.437091403894819, reg_alpha= 2.253803670031582,reg_lambda= 11.129358439611085)

# best_model = XGBClassifier(**params)

best_model.fit(x_train_s,y_train_s)

pred = best_model.predict(x_test)

acc = accuracy_score(y_test,pred)
rec = recall_score(y_test,pred)
pre = precision_score(y_test,pred)

print(f"Accuracy Score: {acc}\n Recall Score: {rec} \n Precision Score: {pre}")
print(classification_report(y_test,pred))

Accuracy Score: 0.9420289855072463
 Recall Score: 0.9830508474576272
 Precision Score: 0.9508196721311475
              precision    recall  f1-score   support

           0       0.88      0.70      0.78        10
           1       0.95      0.98      0.97        59

    accuracy                           0.94        69
   macro avg       0.91      0.84      0.87        69
weighted avg       0.94      0.94      0.94        69

### Save Model

In [45]:
import pickle
with open('model.pkl','wb') as f:
        pickle.dump(best_model,f)

In [47]:
with open("model.pkl","rb") as f:
    model = pickle.load(f)